spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/booksharesystem?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: manmeng
  redis:
    host: 120.78.214.227
    port: 6379
    password: manmeng
druid:
  driver-class: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/booksharesystem?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=true
  user: root
  password: manmeng
  initial-size: 20
  min-idle: 20
  max-active: 200
  max-wait: 60000
  time-between-eviction-runs-millis: 60000
  min-evictable-idle-time-millis: 300000
  test-while-idle: true
  test-on-borrow: falsem
  test-on-return: false
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml